core/urls.py
from __future__ import unicode_literals

from django.conf.urls import url

from . import views


urlpatterns = [
    url(r'^$', views.home, name='home'),
    url(r'^style-guide/', views.styleguide, name='styleguide'),
]

dashboard/product/urls.py
from __future__ import unicode_literals

from django.conf.urls import url

from . import views


urlpatterns = [
    url(r'^$',
        views.product_list, name='product-list'),
    url(r'^(?P<pk>[0-9]+)/$',
        views.product_detail, name='product-detail'),
    url(r'^(?P<pk>[0-9]+)/publish/$', views.product_toggle_is_published,
        name='product-publish'),
    url(r'^(?P<pk>[0-9]+)/update/$',
        views.product_edit, name='product-update'),
    url(r'^(?P<pk>[0-9]+)/delete/$',
        views.product_delete, name='product-delete'),
    url(r'^add/(?P<class_pk>[0-9]+)/$',
        views.product_create, name='product-add'),
    url(r'^bulk-update/$',
        views.product_bulk_update, name='product-bulk-update'),

    url(r'^classes/$',
        views.product_class_list, name='product-class-list'),
    url(r'^classes/add/$',
        views.product_class_create, name='product-class-add'),
    url(r'^classes/(?P<pk>[0-9]+)/update/$',
        views.product_class_edit, name='product-class-update'),
    url(r'^classes/(?P<pk>[0-9]+)/delete/$',
        views.product_class_delete, name='product-class-delete'),

    url(r'^(?P<product_pk>[0-9]+)/variants/add/$',
        views.variant_edit, name='variant-add'),
    url(r'^(?P<product_pk>[0-9]+)/variants/(?P<variant_pk>[0-9]+)/$',
        views.variant_details, name='variant-details'),
    url(r'^(?P<product_pk>[0-9]+)/variants/(?P<variant_pk>[0-9]+)/update/$',
        views.variant_edit, name='variant-update'),
    url(r'^(?P<product_pk>[0-9]+)/variants/(?P<variant_pk>[0-9]+)/delete/$',
        views.variant_delete, name='variant-delete'),
    url(r'^(?P<product_pk>[0-9]+)/variants/(?P<variant_pk>[0-9]+)/images/$',
        views.variant_images, name='variant-images'),

    url(r'^(?P<product_pk>[0-9]+)/variants/(?P<variant_pk>[0-9]+)/stock/add/$',
        views.stock_edit, name='variant-stock-add'),
    url(r'^(?P<product_pk>[0-9]+)/variants/(?P<variant_pk>[0-9]+)/stock/'
        r'(?P<stock_pk>[0-9]+)/$',
        views.stock_details, name='variant-stock-details'),
    url(r'^(?P<product_pk>[0-9]+)/variants/(?P<variant_pk>[0-9]+)/stock/'
        r'(?P<stock_pk>[0-9]+)/update/$',
        views.stock_edit, name='variant-stock-update'),
    url(r'^(?P<product_pk>[0-9]+)/variants/(?P<variant_pk>[0-9]+)/stock/'
        r'(?P<stock_pk>[0-9]+)/delete/$',
        views.stock_delete, name='variant-stock-delete'),

    url(r'^(?P<product_pk>[0-9]+)/images/$', views.product_images,
        name='product-image-list'),
    url(r'^(?P<product_pk>[0-9]+)/images/(?P<img_pk>[0-9]+)/$',
        views.product_image_edit, name='product-image-update'),
    url(r'^(?P<product_pk>[0-9]+)/images/add/$',
        views.product_image_edit, name='product-image-add'),
    url(r'^(?P<product_pk>[0-9]+)/images/(?P<img_pk>[0-9]+)/delete/$',
        views.product_image_delete, name='product-image-delete'),

    url(r'^(?P<product_pk>[0-9]+)/images/reorder/$',
        views.ajax_reorder_product_images, name='product-images-reorder'),
    url(r'^(?P<product_pk>[0-9]+)/images/upload/$',
        views.ajax_upload_image, name='product-images-upload'),

    url(r'attributes/$',
        views.attribute_list, name='product-attributes'),
    url(r'attributes/(?P<pk>[0-9]+)/$',
        views.attribute_detail, name='product-attribute-detail'),
    url(r'attributes/(?P<pk>[0-9]+)/update/$',
        views.attribute_edit, name='product-attribute-update'),
    url(r'attributes/add/$',
        views.attribute_edit, name='product-attribute-add'),
    url(r'attributes/(?P<pk>[0-9]+)/delete/$',
        views.attribute_delete, name='product-attribute-delete'),
    url(r'attributes/(?P<attribute_pk>[0-9]+)/value/(?P<value_pk>[0-9]+)/update/$',  # noqa
        views.attribute_choice_value_edit,
        name='product-attribute-value-update'),
    url(r'attributes/(?P<attribute_pk>[0-9]+)/value/add/$',
        views.attribute_choice_value_edit,
        name='product-attribute-value-add'),
    url(r'attributes/(?P<attribute_pk>[0-9]+)/value/(?P<value_pk>[0-9]+)/delete/$',  # noqa
        views.attribute_choice_value_delete,
        name='product-attribute-value-delete'),

    url(r'stocklocations/$', views.stock_location_list,
        name='product-stock-location-list'),
    url(r'stocklocations/add/$', views.stock_location_edit,
        name='product-stock-location-add'),
    url(r'stocklocations/(?P<location_pk>[0-9]+)/$', views.stock_location_edit,
        name='product-stock-location-edit'),
    url(r'stocklocations/(?P<location_pk>[0-9]+)/delete/$',
        views.stock_location_delete, name='product-stock-location-delete'),

    url(r'^ajax/variants/$',
        views.ajax_available_variants_list, name='ajax-available-variants'),
]

home/urls.py
from __future__ import unicode_literals

from django.conf.urls import url, include

from products.urls import urlpatterns as product_urls

from . import views


urlpatterns = [
	url(r'^$',
		views.home, name='home'),
	url(
		r'^products/',
		include((product_urls, 'product'), namespace='product')),
]

personalized4niture/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
	url(r'^', include('home.urls')),
	url(r'^markdownx/', include('markdownx.urls')),
	url(r'^admin/', admin.site.urls),
]

if settings.DEBUG:
	urlpatterns += static(settings.STATIC_URL,
						  document_root=settings.STATIC_ROOT)
	urlpatterns += static(settings.MEDIA_URL,
						  document_root=settings.MEDIA_ROOT)

products/urls.py
from __future__ import unicode_literals

from django.conf.urls import url

from . import views


urlpatterns = [
	url(r'^(?P<slug>[a-z0-9-_]+?)-(?P<product_id>[0-9]+)/$',
		views.product_details, name='details'),
	url(r'^category/(?P<path>[a-z0-9-_/]+?)-(?P<category_id>[0-9]+)/$',
		views.category_index, name='category'),
	url(r'(?P<slug>[a-z0-9-_]+?)-(?P<product_id>[0-9]+)/add/$',
		views.product_add_to_cart, name="add-to-cart"),
]

products/forms.py
from __future__ import unicode_literals

import json

from django import forms
from django.utils.encoding import smart_text
from django.utils.translation import pgettext_lazy
from django_prices.templatetags.prices_i18n import gross

from carts.forms import AddToCartForm


class VariantChoiceField(forms.ModelChoiceField):
    discounts = None

    def label_from_instance(self, obj):
        variant_label = smart_text(obj)
        label = pgettext_lazy(
            'Variant choice field label',
            '%(variant_label)s - %(price)s') % {
                'variant_label': variant_label,
                'price': gross(obj.get_price(discounts=self.discounts))}
        return label


class ProductForm(AddToCartForm):
    variant = VariantChoiceField(queryset=None)

    def __init__(self, *args, **kwargs):
        super(ProductForm, self).__init__(*args, **kwargs)
        variant_field = self.fields['variant']
        variant_field.queryset = self.product.variants
        variant_field.discounts = self.cart.discounts
        variant_field.empty_label = None
        images_map = {variant.pk: [vi.image.image.url
                                   for vi in variant.variant_images.all()]
                      for variant in self.product.variants.all()}
        variant_field.widget.attrs['data-images'] = json.dumps(images_map)

    def get_variant(self, cleaned_data):
        return cleaned_data.get('variant')

dashboard/product/views.py
from __future__ import unicode_literals

from django.conf import settings
from django.contrib import messages
from django.contrib.auth.decorators import permission_required
from django.db.models import Q
from django.http import JsonResponse
from django.shortcuts import get_object_or_404, redirect
from django.template.response import TemplateResponse
from django.utils.translation import npgettext_lazy, pgettext_lazy
from django.views.decorators.http import require_POST
from django_prices.templatetags.prices_i18n import gross

from ...core.utils import get_paginator_items
from ...product.models import (
    AttributeChoiceValue, Product, ProductAttribute, ProductClass,
    ProductImage, ProductVariant, Stock, StockLocation)
from ...product.utils import (
    get_availability, get_product_costs_data, get_variant_costs_data)
from ..views import staff_member_required
from .filters import (
    ProductFilter, ProductAttributeFilter, ProductClassFilter,
    StockLocationFilter)
from . import forms


@staff_member_required
@permission_required('product.view_properties')
def product_class_list(request):
    classes = ProductClass.objects.all().prefetch_related(
        'product_attributes', 'variant_attributes').order_by('name')
    class_filter = ProductClassFilter(request.GET, queryset=classes)
    form = forms.ProductClassForm(request.POST or None)
    if form.is_valid():
        return redirect('dashboard:product-class-add')
    classes = get_paginator_items(
        class_filter.qs, settings.DASHBOARD_PAGINATE_BY,
        request.GET.get('page'))
    classes.object_list = [
        (pc.pk, pc.name, pc.has_variants, pc.product_attributes.all(),
         pc.variant_attributes.all())
        for pc in classes.object_list]
    ctx = {'form': form, 'product_classes': classes, 'filter': class_filter}
    return TemplateResponse(
        request,
        'dashboard/product/product_class/list.html',
        ctx)


@staff_member_required
@permission_required('product.edit_properties')
def product_class_create(request):
    product_class = ProductClass()
    form = forms.ProductClassForm(request.POST or None,
                                  instance=product_class)
    if form.is_valid():
        product_class = form.save()
        msg = pgettext_lazy(
            'Dashboard message', 'Added product type %s') % product_class
        messages.success(request, msg)
        return redirect('dashboard:product-class-list')
    ctx = {'form': form, 'product_class': product_class}
    return TemplateResponse(
        request,
        'dashboard/product/product_class/form.html',
        ctx)


@staff_member_required
@permission_required('product.edit_properties')
def product_class_edit(request, pk):
    product_class = get_object_or_404(
        ProductClass, pk=pk)
    form = forms.ProductClassForm(request.POST or None,
                                  instance=product_class)
    if form.is_valid():
        product_class = form.save()
        msg = pgettext_lazy(
            'Dashboard message', 'Updated product type %s') % product_class
        messages.success(request, msg)
        return redirect('dashboard:product-class-update', pk=pk)
    ctx = {'form': form, 'product_class': product_class}
    return TemplateResponse(
        request,
        'dashboard/product/product_class/form.html',
        ctx)


@staff_member_required
@permission_required('product.edit_properties')
def product_class_delete(request, pk):
    product_class = get_object_or_404(ProductClass, pk=pk)
    if request.method == 'POST':
        product_class.delete()
        messages.success(
            request,
            pgettext_lazy(
                'Dashboard message',
                'Removed product type %s') % product_class)
        return redirect('dashboard:product-class-list')
    ctx = {
        'product_class': product_class,
        'products': product_class.products.all()}
    return TemplateResponse(
        request,
        'dashboard/product/product_class/modal/confirm_delete.html',
        ctx)


@staff_member_required
@permission_required('product.view_product')
def product_list(request):
    products = Product.objects.prefetch_related('images')
    products = products.order_by('name')
    product_classes = ProductClass.objects.all()

    form = forms.ProductClassSelectorForm(
        request.POST or None, product_classes=product_classes)
    if form.is_valid():
        return redirect(
            'dashboard:product-add', class_pk=form.cleaned_data['product_cls'])
    product_filter = ProductFilter(request.GET, queryset=products)
    products = get_paginator_items(
        product_filter.qs, settings.DASHBOARD_PAGINATE_BY,
        request.GET.get('page'))
    ctx = {
        'bulk_action_form': forms.ProductBulkUpdate(), 'form': form,
        'products': products, 'product_classes': product_classes,
        'filter': product_filter,
    }
    return TemplateResponse(request, 'dashboard/product/list.html', ctx)


@staff_member_required
@permission_required('product.edit_product')
def product_create(request, class_pk):
    product_class = get_object_or_404(ProductClass, pk=class_pk)
    create_variant = not product_class.has_variants
    product = Product()
    product.product_class = product_class
    product_form = forms.ProductForm(request.POST or None, instance=product)
    if create_variant:
        variant = ProductVariant(product=product)
        variant_form = forms.ProductVariantForm(
            request.POST or None, instance=variant, prefix='variant')
        variant_errors = not variant_form.is_valid()
    else:
        variant_form = None
        variant_errors = False

    if product_form.is_valid() and not variant_errors:
        product = product_form.save()
        if create_variant:
            variant.product = product
            variant_form.save()
        msg = pgettext_lazy(
            'Dashboard message', 'Added product %s') % product
        messages.success(request, msg)
        return redirect('dashboard:product-detail', pk=product.pk)
    ctx = {
        'product_form': product_form, 'variant_form': variant_form,
        'product': product}
    return TemplateResponse(request, 'dashboard/product/form.html', ctx)


@staff_member_required
@permission_required('product.view_product')
def product_detail(request, pk):
    products = Product.objects.prefetch_related(
        'variants__stock', 'images',
        'product_class__variant_attributes__values').all()
    product = get_object_or_404(products, pk=pk)
    variants = product.variants.all()
    images = product.images.all()
    availability = get_availability(product)
    sale_price = availability.price_range
    purchase_cost, gross_margin = get_product_costs_data(product)
    gross_price_range = product.get_gross_price_range()

    # no_variants is True for product classes that doesn't require variant.
    # In this case we're using the first variant under the hood to allow stock
    # management.
    no_variants = not product.product_class.has_variants
    only_variant = variants.first() if no_variants else None
    if only_variant:
        stock = only_variant.stock.all()
    else:
        stock = Stock.objects.none()
    ctx = {
        'product': product, 'sale_price': sale_price, 'variants': variants,
        'gross_price_range': gross_price_range, 'images': images,
        'no_variants': no_variants, 'only_variant': only_variant,
        'stock': stock, 'purchase_cost': purchase_cost,
        'gross_margin': gross_margin}
    return TemplateResponse(request, 'dashboard/product/detail.html', ctx)


@require_POST
@staff_member_required
@permission_required('product.edit_product')
def product_toggle_is_published(request, pk):
    product = get_object_or_404(Product, pk=pk)
    product.is_published = not product.is_published
    product.save(update_fields=['is_published'])
    return JsonResponse(
        {'success': True, 'is_published': product.is_published})


@staff_member_required
@permission_required('product.edit_product')
def product_edit(request, pk):
    product = get_object_or_404(
        Product.objects.prefetch_related('variants'), pk=pk)

    edit_variant = not product.product_class.has_variants
    form = forms.ProductForm(request.POST or None, instance=product)

    if edit_variant:
        variant = product.variants.first()
        variant_form = forms.ProductVariantForm(
            request.POST or None, instance=variant, prefix='variant')
        variant_errors = not variant_form.is_valid()
    else:
        variant_form = None
        variant_errors = False

    if form.is_valid() and not variant_errors:
        product = form.save()
        if edit_variant:
            variant_form.save()
        msg = pgettext_lazy(
            'Dashboard message', 'Updated product %s') % product
        messages.success(request, msg)
        return redirect('dashboard:product-detail', pk=product.pk)
    ctx = {'product': product, 'product_form': form,
           'variant_form': variant_form}
    return TemplateResponse(request, 'dashboard/product/form.html', ctx)


@staff_member_required
@permission_required('product.edit_product')
def product_delete(request, pk):
    product = get_object_or_404(Product, pk=pk)
    if request.method == 'POST':
        product.delete()
        messages.success(
            request,
            pgettext_lazy('Dashboard message', 'Removed product %s') % product)
        return redirect('dashboard:product-list')
    return TemplateResponse(
        request,
        'dashboard/product/modal/confirm_delete.html',
        {'product': product})


@staff_member_required
@permission_required('product.view_stock_location')
def stock_details(request, product_pk, variant_pk, stock_pk):
    product = get_object_or_404(Product, pk=product_pk)
    variant = get_object_or_404(product.variants, pk=variant_pk)
    stock = get_object_or_404(variant.stock, pk=stock_pk)
    ctx = {'stock': stock, 'product': product, 'variant': variant}

templates/product/_price_range.html
{% load i18n %}
{% load gross from prices_i18n %}

<span>
    <span>
        {% if price_range.min_price != price_range.max_price %}{% trans "from" context "product price range" %} {% endif %}{% gross price_range.min_price html=True %}
    </span>
</span>

templates/product/details.html
{% extends "base.html" %}

{% load bootstrap_field from bootstrap3 %}
{% load i18n %}
{% load gross from prices_i18n %}
{% load markdown from markdown %}
{% load price_range from price_ranges %}
{% load staticfiles %}
{% load get_thumbnail from product_images %}

{% block title %}{{ product }} — {{ block.super }}{% endblock %}

{% block meta_description %}{{ product.description }}{% endblock %}

{% block breadcrumb %}
  <ul class="breadcrumbs list-unstyled">
    <li><a href="/">
        {% trans "Home" context "Main navigation item" %}
    </a></li>
    {% with product.get_first_category as category %}
      {% if category %}
        <li><a href="{{ category.get_absolute_url }}">{{ category }}</a></li>
      {% endif %}
    {% endwith %}
    <li><a href="{{ product.get_absolute_url }}">{{ product }}</a></li>
  </ul>
{% endblock breadcrumb %}

{% block content %}
  {% if not is_visible %}
    <div class="alert alert-warning" role="alert">
      {% blocktrans trimmed with date=product.available_on|date context "Product details text" %}
          <strong>Warning!</strong>
          You are previewing a product that will become visible on <strong>{{ date }}</strong>.
      {% endblocktrans %}
    </div>
  {% endif %}
  <div class="row product">
    <div id="product-schema-component">
      <script type="application/ld+json">{{ json_ld_product_data|safe }}</script>
    </div>
    <div class="col-md-6 col-12 product__gallery">
      {% with images=product_images %}
        {% if images %}
          <div id="carousel-example-generic" class="carousel slide">
            <div class="carousel-inner" role="listbox">
              {% for image in images %}
                <div class="carousel-item{% if forloop.first %} active{% endif %}">
                  <img class="d-block img-fluid"
                       src="{% get_thumbnail image.image method="crop" size="540x540" %}"
                       srcset="{% get_thumbnail image.image method="crop" size="540x540" %} 1x, {% get_thumbnail image.image method="crop" size="1080x1080" %} 2x" alt="">
                </div>
              {% endfor %}
            </div>
            {% if images|length > 1 %}
              <a class="carousel-control-prev" href="#carousel-example-generic" role="button" data-slide="prev">
                <svg data-src="{% static "images/gallery_arrow.svg" %}" />
              </a>
              <a class="carousel-control-next" href="#carousel-example-generic" role="button" data-slide="next">
                <svg data-src="{% static "images/gallery_arrow.svg" %}" />
              </a>
            {% endif %}
            <ol class="carousel-indicators hidden-sm-down">
              {% for image in images %}
                {% if images|length > 1 %}
                  <li data-target="#carousel-example-generic" data-slide-to="{{ forloop.counter0 }}"{% if forloop.first %} class="active"{% endif %}>
                    <img src="{% get_thumbnail image.image method="crop" size="60x60" %}"
                         srcset="{% get_thumbnail image.image method="crop" size="60x60" %} 1x, {% get_thumbnail image.image method="crop" size="120x120" %} 2x"
                         alt="">
                  </li>
                {% endif %}
              {% endfor %}
            </ol>
          </div>
        {% else %}
          <img src="{% static 'images/placeholder540x540.png' %}"
               srcset="{% static 'images/placeholder540x540.png' %} 1x, {% static 'images/placeholder1080x1080.png' %} 2x"
               alt=""
               class="img-fluid">
        {% endif %}
      {% endwith %}
    </div>
    <div class="col-md-6 col-12 product__info">
      <h1 class="product__info__name">
        {{ product }}
      </h1>
      {% if user.is_staff %}
        <p><a href="{% url "dashboard:product-detail" pk=product.pk %}">
            {% trans "Edit in dashboard" context "Product details link text" %}
        </a></p>
      {% endif %}
      {% if availability.available %}
        {% if show_variant_picker %}
          <div id="variant-price-component"></div>
        {% else %}
          <h2 class="product__info__price">
            <span>{% price_range availability.price_range %}</span>
            {% if availability.discount %}
              <small class="product__info__price__undiscounted">{% gross availability.price_range_undiscounted.min_price html=True %}</small>
            {% endif %}
            {% if availability.price_range_local_currency %}
              <br>
              <small class="text-info">
                &asymp;
                {% gross availability.price_range_local_currency.min_price html=True %}
              </small>
            {% endif %}
          </h2>
        {% endif %}
      {% endif %}
      {% if is_visible and product.is_in_stock %}
        {% block orderform %}
          {% if show_variant_picker %}
            {% csrf_token %}
            <div id="variant-picker" data-variant-picker-data="{{ variant_picker_data }}" data-action="{% url 'product:add-to-cart' product_id=product.pk slug=product.get_slug %}"></div>
          {% else %}
            <form id="product-form" role="form" class="product-form clearfix" method="post"
                  action="{% url 'product:add-to-cart' product_id=product.pk slug=product.get_slug %}" novalidate>
              {% csrf_token %}
              {% bootstrap_field form.variant %}
              <div class="product__info__quantity">
                {% bootstrap_field form.quantity %}
              </div>

              <div class="form-group product__info__button">
                <button class="btn primary">
                  {% trans "Add to cart" context "Product details primary action" %}
                </button>
              </div>
            </form>
          {% endif %}
        {% endblock %}
        <div class="product__info__form-error">
          <small class="text-danger"></small>
        </div>

      {% else %}
        <p class="alert alert-warning">
          {% blocktrans context "Product details text" %}This product is currently <strong>unavailable</strong>.{% endblocktrans %}
        </p>
      {% endif %}
      <div class="product__info__description">
        <h3>{% trans "Description" context "Product details title" %}</h3>
        <hr>
        {{ product.description|markdown }}
      </div>
      <hr>
      <table>
        {% for attribute, value in product_attributes.items %}
          <tr>
            <td>{{ attribute }}:</td>
            <td><strong>{{ value }}</strong></td>
          </tr>
        {% endfor %}
      </table>
    </div>
  </div>
{% endblock content %}

templates/product/products_home.html
{% load static %}
<section id="products">
    <div class="container-fluid">
        <div class="row">
            <div class="col-sm-12 section-heading-wrap text-center">
                <h2 class="section-heading">New Furniture Arrival</h2>
                <h4 class="section-subheading">Home to the Finest Interior Design Products in the World</h4>
            </div>
        </div>
          {% for furniture in furnitures %}
      		{% if forloop.first %}
					<div class="row">
						{% endif %}
          <div class="col-md-3 col-sm-6 col-xs-12 no-padding">
            <figure class="wow fadeIn">
              {% if furniture.image %}
                <img class="img-responsive" src={{ furniture.image.url }} alt="furniture">
                {% else %}
                <img class="img-responsive" src={% static 'img/4niture.jpg' %} alt="furniture">
                {% endif %}
                <figcaption>
                    <a href="{% url 'furniture' furniture.slug%}">
                        <h5 class="product-title">{{ furniture.name }}</h5>
                        <h4 class="product-price"><del>{{ furniture.old_price}}</del><span class="promo-price">Rs. {{furniture.price}}</span></h4>
                        <p class="product-details">{{ furniture.gist }}</p>
                    </a>
                </figcaption>
            </figure>
					</div>
            {% if forloop.counter|divisibleby:4 %}
					</div>
            <div class="row">{%endif %}
              {% if forloop.last %}
            </div>
      		{% endif %}
      		{% endfor %}
        </div>
    </div>
</section>